name: Find signed commits

on:
  push:  
jobs:          
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - uses: live627/upload-file-action@master
        with:
          hostname: simplemachines.org
          path: /
          upfile: README.md
