name: Find signed commits

on:
  pull_request_target:

jobs:
  remove-label:
    name: Write comment if unsigned commits found
    env:
      FORCE_COLOR: 1
    runs-on: ubuntu-latest
    steps:
      - uses: live627/upload-release-asset@main
