name: Find signed commits

on:
  push:  
jobs:          
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: node server.js & sleep 1
      - uses: live627/upload-file-action@master
        with:
          hostname: localhost:8086
          path: /
          upfile: README.md
          metdata: |
            var: val
            var1: val1
