name: Find signed commits

on:
  push:  
jobs:          
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: php -S localhost:8000 b.php & sleep 1
      - uses: live627/upload-file-action@master
        with:
          hostname: localhost:8000
          path: /
          upfile: README.md
